name: Test
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: create item
        run: New-Item test.txt
        working-directory: "C:/Users/rasal/Desktop"
