name: Test
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - run: cd "C:\Users\rasal\Desktop"
      - run: New-Item test.txt
